import Footer from "/components/Footer";
import Header from "/components/Header";
import Head from "next/head";
import styles from "/styles/Download.module.css";
import Image from "next/image";
import Link from "next/link";

export default function Download() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD"
          crossorigin="anonymous"
        ></link>
      </Head>

      <Header></Header>

      <div className={styles.main_title_box}>
        <div className={styles.main_image}> </div>
        <h1 className={styles.main_title}>Download</h1>
      </div>

      <div className={styles.main_box}>
        <div className={styles.content_box}>
          <h1 className={styles.title_box}>Télécharger le projet</h1>
          <div className={styles.main_description}>
            <p>
              Si vous souhaitez tester les fonctionnalités du projet, vous
              pouvez le télécharger sur le GitHub ci-dessous :
            </p>
          </div>

          <div className={styles.big_card_box}>
            <div className={styles.big_card}>
              <div className={styles.github_image_box}>
                <Image
                  src="/github.png"
                  width={500}
                  height={500}
                  className={styles.robot_image}
                />
              </div>
              <div className={styles.big_card_text}>
                <h2>Github</h2>
                <p>
                  Le <b>Github</b> du projet est disponible en cliquant{" "}
                  <Link
                    href="https://github.com/mines-nancy/projet_lucas_bertinchamp"
                    className={styles.link}
                  >
                    ici
                  </Link>
                </p>
                <p>
                  Depuis un terminal, vous pouvez le cloner sur votre machine en
                  utilisant la commande suivante :
                </p>
                <code>
                  git clone
                  https://github.com/mines-nancy/projet_lucas_bertinchamp.git
                </code>
                <br />
                <p>
                  La version à jour du projet est disponible sur la branche
                  <b>"Lucas"</b>
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>

      <script
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
        crossorigin="anonymous"
        async
      ></script>

      <Footer></Footer>
    </>
  );
}
