import Footer from "../components/Footer";
import Header from "../components/Header";
import Head from "next/head";
import styles from "/styles/Faq.module.css";
import { useUser } from "@auth0/nextjs-auth0/client";
import Image from "next/image";
import Link from "next/link";
import Question from "../components/Question";


export default function Download() {
  const { user, isLoading } = useUser();
  /*
  const client = new Client({
    connectionString: process.env.DATABASE_URL,
    ssl: {
      rejectUnauthorized: false,
    },
  });

  client.connect();

  client.query(
    "SELECT table_schema,table_name FROM information_schema.tables;",
    (err, res) => {
      if (err) throw err;
      for (let row of res.rows) {
        console.log(JSON.stringify(row));
      }
      client.end();
    }
  );*/

  let question = {
    title: "En quoi consiste le projet ?",
    id: 1,
    date: "12/12/2021",
    content: "Bonjour je suis une question écrite par défaut",
    upvotes: 0,
    author: {
      mail: "",
      name: "Jean",
      surname: "Dupont",
      picture:
        "https://cdn.auth0.com/blog/auth0-react-sample/assets/profile.png",
    },
  };

  if (isLoading) return <div>Loading...</div>;
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD"
          crossorigin="anonymous"
        ></link>
      </Head>

      <Header></Header>

      <div className={styles.main_title_box}>
        <div className={styles.main_image}> </div>
        <h1 className={styles.main_title}>FAQs</h1>
      </div>

      {!user && (
        <div className={styles.main_page_box_disconnected}>
          <div className={styles.main_page_disconnected}>
            <h2 className={styles.main_page_title}>Vous n'êtes pas connecté</h2>
            <p className={styles.main_page_text}>
              Vous devez être connecté pour accéder à cette page.
            </p>

            <Link href="/api/auth/login">
              <button type="button" className="btn btn-primary">
                Log-in
              </button>
            </Link>
          </div>
        </div>
      )}

      {user && (
        <div className={styles.main_page_box_connected}>
          <div className={styles.main_page_connected}>
            <h2 className={styles.main_page_title}>FAQ</h2>
            <p className={styles.main_page_text}>
              Sur cette page, vous pouvez poser vos questions et obtenir des
              réponses par d'autres utilisateurs. Vous pouvez également
              consulter les questions et réponses déjà posées.
            </p>

            <div className={styles.send_question_box}>
              <h3 className={styles.send_question_title}>Poser une question</h3>
              <p className={styles.send_question_text}>
                Vous pouvez poser une question à l'aide de ce formulaire :
              </p>
              <form>
                <div className="form-group">
                  <textarea
                    class="form-control"
                    id="exampleFormControlTextarea1"
                    rows="1"
                    placeholder="Titre de la question"
                  ></textarea>
                  <textarea
                    class="form-control"
                    id="exampleFormControlTextarea1"
                    rows="3"
                  ></textarea>
                </div>
              </form>
              <button type="button" className="btn btn-primary">
                Envoyer
              </button>
            </div>

            <hr></hr>

            <div className={styles.questions_box}>
              <h3 className={styles.questions_title}>Questions</h3>
              <Question data={question}></Question>
            </div>
          </div>
        </div>
      )}

      <script
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
        crossorigin="anonymous"
        async
      ></script>

      <Footer></Footer>
    </>
  );
}
